### ISSUE TITLE
[Bug] Crashes when using shaders + resourcepack.

### ISSUE THREAD

**Issue by vitorwille** [Dimples-1337/FDPClient#1235]
**Describe the bug**
Game crashes after some time using shaderpacks with a resourcepack.

**To Reproduce**
1. Install a shaderpack and a resourcepack.
2. Enable them.
3. Go to PikaNetwork, open the menu and click on "bedwars".

**Expected behavior**
Play normally.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin ([Medusa] MemoryFix.jar)
  TransformerLoader (skiddy-cbeta.jar)
  TLSkinCapeHookLoader (tlskincape_1.8.9-1.4.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 16/03/22 22:18
Description: Tesselating block model

java.lang.ArrayIndexOutOfBoundsException: -272
	at net.minecraft.client.renderer.RegionRenderCache.func_180495_p(RegionRenderCache.java:72)
	at net.optifine.override.ChunkCacheOF.func_180495_p(ChunkCacheOF.java:147)
	at net.minecraft.block.BlockStairs.func_176306_h(BlockStairs.java:343)
	at net.minecraft.block.BlockStairs.func_176221_a(BlockStairs.java:721)
	at net.minecraft.block.Block.isSideSolid(Block.java:1105)
	at net.minecraft.block.BlockPane.canPaneConnectTo(BlockPane.java:197)
	at net.minecraft.block.BlockPane.func_176221_a(BlockPane.java:43)
	at net.optifine.ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1648)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1615)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1595)
	at net.optifine.ConnectedTextures.getConnectedTextureCtmIndex(ConnectedTextures.java:1201)
	at net.optifine.ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:825)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:578)
	at net.optifine.ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:400)
	at net.optifine.ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:329)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:123)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:113)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:67)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelFlat(BlockModelRenderer.java:189)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:74)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:53)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:316)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.RegionRenderCache.func_180495_p(RegionRenderCache.java:72)
	at net.optifine.override.ChunkCacheOF.func_180495_p(ChunkCacheOF.java:147)
	at net.minecraft.block.BlockStairs.func_176306_h(BlockStairs.java:343)
	at net.minecraft.block.BlockStairs.func_176221_a(BlockStairs.java:721)
	at net.minecraft.block.Block.isSideSolid(Block.java:1105)
	at net.minecraft.block.BlockPane.canPaneConnectTo(BlockPane.java:197)
	at net.minecraft.block.BlockPane.func_176221_a(BlockPane.java:43)
	at net.optifine.ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1648)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1615)
	at net.optifine.ConnectedTextures.isNeighbour(ConnectedTextures.java:1595)
	at net.optifine.ConnectedTextures.getConnectedTextureCtmIndex(ConnectedTextures.java:1201)
	at net.optifine.ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:825)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:578)
	at net.optifine.ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:400)
	at net.optifine.ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:329)
	at net.optifine.ConnectedTextures.getConnectedTexture(ConnectedTextures.java:123)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:113)
	at net.optifine.model.BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:67)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelFlat(BlockModelRenderer.java:189)

-- Block model being tesselated --
Details:
	Block: minecraft:stained_glass_pane[color=blue,east=false,north=false,south=false,west=false]
	Block location: World: (0,70,4), Chunk: (at 0,4,4 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:74)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:53)

-- Block being tesselated --
Details:
	Block type: ID #160 (tile.thinStainedGlass // net.minecraft.block.BlockStainedGlassPane)
	Block data value: 11 / 0xB / 0b1011
	Block location: World: (0,70,4), Chunk: (at 0,4,4 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)

-- Affected level --
Details:
	Level name: MpServer
	All players: 9 total; [EntityPlayerSP['kkkkkvitokkkkk'/1031463, l='MpServer', x=0,51, y=60,00, z=13,51], EntityOtherPlayerMP['Khanhmamaa'/801324, l='MpServer', x=9,31, y=61,00, z=9,22], EntityOtherPlayerMP['AlekDoHaxa'/768032, l='MpServer', x=1,09, y=60,00, z=15,09], EntityOtherPlayerMP['swazaza'/799036, l='MpServer', x=0,50, y=60,00, z=13,50], EntityOtherPlayerMP['NameItRicky'/805471, l='MpServer', x=0,50, y=60,00, z=13,50], EntityOtherPlayerMP['gigto'/713586, l='MpServer', x=0,50, y=60,00, z=13,50], EntityOtherPlayerMP['§r'/1005, l='MpServer', x=0,53, y=60,00, z=6,53], EntityOtherPlayerMP['Adam19992002'/802667, l='MpServer', x=0,16, y=60,00, z=19,28], EntityOtherPlayerMP['§r'/1014, l='MpServer', x=-5,50, y=60,00, z=19,50]]
	Chunk stats: MultiplayerChunkCache: 10, 10
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -421,00,64,00,774,00 - World: (-421,64,774), Chunk: (at 11,4,6 in -27,48; contains blocks -432,0,768 to -417,255,783), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 94532735 game time, 361200 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 27 total; [EntityArmorStand['Armor Stand'/1024, l='MpServer', x=-5,50, y=62,00, z=19,50], EntityArmorStand['§e§lRight Click §fto open this NPC!'/1025, l='MpServer', x=-5,50, y=61,75, z=19,50], EntityOtherPlayerMP['NameItRicky'/805471, l='MpServer', x=0,50, y=60,00, z=13,50], EntityOtherPlayerMP['Khanhmamaa'/801324, l='MpServer', x=9,31, y=61,00, z=9,22], EntityOtherPlayerMP['Adam19992002'/802667, l='MpServer', x=0,16, y=60,00, z=19,28], EntityOtherPlayerMP['AlekDoHaxa'/768032, l='MpServer', x=1,09, y=60,00, z=15,09], EntityPlayerSP['kkkkkvitokkkkk'/1031463, l='MpServer', x=0,51, y=60,00, z=13,51], EntityOtherPlayerMP['§r'/1005, l='MpServer', x=0,53, y=60,00, z=6,53], EntityOtherPlayerMP['Khanhmamaa'/801324, l='MpServer', x=9,31, y=61,00, z=9,22], EntityOtherPlayerMP['AlekDoHaxa'/768032, l='MpServer', x=1,09, y=60,00, z=15,09], EntityOtherPlayerMP['swazaza'/799036, l='MpServer', x=0,50, y=60,00, z=13,50], EntityOtherPlayerMP['swazaza'/799036, l='MpServer', x=0,50, y=60,00, z=13,50], EntityArmorStand['§e§lReturn Hub'/1008, l='MpServer', x=0,53, y=61,91, z=6,53], EntityOtherPlayerMP['NameItRicky'/805471, l='MpServer', x=0,50, y=60,00, z=13,50], EntityOtherPlayerMP['gigto'/713586, l='MpServer', x=0,50, y=60,00, z=13,50], EntityOtherPlayerMP['§r'/1005, l='MpServer', x=0,53, y=60,00, z=6,53], EntityOtherPlayerMP['Adam19992002'/802667, l='MpServer', x=0,16, y=60,00, z=19,28], EntityOtherPlayerMP['§r'/1014, l='MpServer', x=-5,50, y=60,00, z=19,50], EntityOtherPlayerMP['gigto'/713586, l='MpServer', x=0,50, y=60,00, z=13,50], EntityOtherPlayerMP['§r'/1014, l='MpServer', x=-5,50, y=60,00, z=19,50], EntityArmorStand['§e§lGold Shop'/1017, l='MpServer', x=-5,50, y=63,75, z=19,50], EntityArmorStand['Armor Stand'/1018, l='MpServer', x=-5,50, y=63,50, z=19,50], EntityArmorStand['§fGold is used in-game to purchase'/1019, l='MpServer', x=-5,50, y=63,25, z=19,50], EntityArmorStand['§fitems on the PikaNetwork Server`s'/1020, l='MpServer', x=-5,50, y=63,00, z=19,50], EntityArmorStand['§fIn-Game Store. You can purchase'/1021, l='MpServer', x=-5,50, y=62,75, z=19,50], EntityArmorStand['§fgold from our webstore at'/1022, l='MpServer', x=-5,50, y=62,50, z=19,50], EntityArmorStand['§a§nstore.pika-network.net'/1023, l='MpServer', x=-5,50, y=62,25, z=19,50]]
	Retry entities: 0 total; []
	Server brand: Waterfall <- PaperSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 360330472 bytes (343 MB) / 1409286144 bytes (1344 MB) up to 3154116608 bytes (3008 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_L5 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	memoryfix{0.3} [MemoryFix] ([Medusa] MemoryFix.jar) 
	UCHIJA	timechanger1.8{1.0} [TimeChanger 1.8] ([Medusa] TimeChanger.jar) 
	UCHIJA	tlauncher_custom_cape_skin{1.4} [TLSkinCape] (tlskincape_1.8.9-1.4.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin ([Medusa] MemoryFix.jar)
  io.prplz.memoryfix.ClassTransformer
TransformerLoader (skiddy-cbeta.jar)
  net.ccbluex.liquidbounce.injection.transformers.ForgeNetworkTransformer
  net.ccbluex.liquidbounce.script.remapper.injection.transformers.AbstractJavaLinkerTransformer
  net.ccbluex.liquidbounce.injection.transformers.ViaForgeSupportTransformer
  net.ccbluex.liquidbounce.injection.transformers.OptimizeTransformer
TLSkinCapeHookLoader (tlskincape_1.8.9-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: Forge 1.8.9
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 5Zign§dFault §f(§55§dK§f).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-Renewed-v1.0.1.zip
	OpenGlVersion: 4.6.0 NVIDIA 511.79
	OpenGlRenderer: NVIDIA GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```

**System Information**
 - OS: Windows 10 21H2
 - Minecraft Version: Forge1.8.9

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- MemoryFix (same issue without it)
- OptiFine (same issue without it)
- TimeChanger (disabled, same issue without it)
- TLSkinCape (same issue without it)

-READ-ME: FDPClient jar file was renamed. Same issue with the original name.

**Comment by HowardZHY** [comment]
try to remove Optifine and retest

**Comment by contionability** [comment]
SEUS do not support 1.8.9 and
maybe GPU Memory Overflow

**Comment by HowardZHY** [comment]
This is more likely to be a Optifine error

**Comment by HowardZHY** [comment]
Your Optifine is outdated , u should try M5
